import * as React from "react";
const SvgComponent = (props) => (
  <g {...props}>
    <defs>
      <style>{".room{fill:#66afe1;stroke:#000;stroke-miterlimit:10;}"}</style>
    </defs>
    <g id="Calque_2" data-name="Calque 2">
      <g id="GACO_1" data-name="GACO 1">
        <rect
          className="room"
          x={0.55}
          y={0.5}
          width={133.05}
          height={325.24}
        />
        <rect
          className="room"
          x={80.82}
          y={225.36}
          width={52.78}
          height={100.48}
        />
        <rect
          className="room"
          x={80.82}
          y={127.77}
          width={52.78}
          height={97.59}
        />
        <rect
          className="room"
          x={80.82}
          y={64.04}
          width={52.78}
          height={63.73}
        />
        <rect
          className="room"
          x={0.5}
          y={225.36}
          width={56.02}
          height={100.48}
        />
        <rect
          className="room"
          x={0.5}
          y={177.16}
          width={56.02}
          height={48.2}
        />
        <rect
          className="room"
          x={0.5}
          y={150.4}
          width={48.25}
          height={26.76}
        />
        <rect
          className="room"
          x={0.5}
          y={84.68}
          width={56.02}
          height={18.39}
        />
        <rect
          className="room"
          x={0.5}
          y={45.71}
          width={56.02}
          height={38.97}
        />
        <rect
          className="room"
          x={35.4}
          y={5.48}
          width={66.92}
          height={30.67}
        />
        <rect
          className="room"
          x={11.9}
          y={325.84}
          width={110.3}
          height={37.28}
          rx={13.02}
        />
      </g>
    </g>
  </g>
);
export default SvgComponent;
